name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      name:
        description: Whom to greet?
        type: string
        required: true
      environment:
        description: Select an environment
        type: string
        required: false
    secrets:
      SSH_KEY:
        required: true

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
        environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: Determine environment
        id: set-environment
        shell: bash
        run: |
          if [ ${{ github.event_name }} == 'push' ]; then
            echo "Pushing to mainbranch, Environment is STAGING"
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "Pull request, Environment is PR"
            echo "environment=pr" >> $GITHUB_OUTPUT
          elif [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            echo "Workflow dispatch, using provided environment: ${{ inputs.environment }}"
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "Unknown event,aborting"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: setup-environment
    environment: ${{ needs.setup-environment.outputs.environment }}
    steps:
      - name: Prepare SSH Environment
        id: setup-ssh
        shell: bash
        env:
          DOCKER_HOST: ${{ vars.DOCKERHOST }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan ${{ vars.HOSTNAME }} > /home/runner/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" | wc -l
          echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
          ls -l /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions
      - name: List Docker images
        run: |
          docker image ls
      - name: List environment
        run: |
          echo "Environment: ${{ needs.setup-environment.outputs.environment }}"
      - name: List Docker host
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo ${{ vars.DOCKERHOST }}
