name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      name:
        description: Who to greet?
        type: string
        required: true
      environment:
        description: Select an environment
        type: string
        required: false

        
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - name: echo event
        run: |
          echo "Event: ${{ github.event_name }}"
      - name: Determine environment
        id: set-environment
        shell: bash
        run: |
          if [ ${{ github.event_name == 'push' }} ]; then
            echo "Pushing to mainbranch, assuming Environment is STAGING"
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [ ${{ github.event_name == 'pull_request' }} ]; then
            echo "Pull request, assuming Environment is PR"
            echo "environment=pr" >> $GITHUB_OUTPUT
          elif [ ${{ github.event_name == 'workflow_dispatch' }} ]; then
            echo "Workflow dispatch, using provided environment: ${{ inputs.environment }}"
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "Unknown event,aborting"
            exit 1
          fi

  greet:
    runs-on: ubuntu-latest
    environment: ${{ needs.setup-environment.outputs.environment }}
    needs: setup-environment
    steps:
      - name: Greet
        run: |
          echo "Hello ${{ inputs.name }}!"
      - name: List environment
        run: |
          echo "Environment: ${{ steps.set-environment.outputs.environment }}"
      - name: List Docker host
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo ${{ vars.DOCKERHOST }}
